#!/bin/bash
# Organize Video Game media files into proper asset structure

SOURCE_DIR="assets/Video Game media"
DEST_BASE="assets"

# Create destination directories
mkdir -p "$DEST_BASE/audio/music"
mkdir -p "$DEST_BASE/audio/sfx"
mkdir -p "$DEST_BASE/sprites/characters"
mkdir -p "$DEST_BASE/sprites/backgrounds"
mkdir -p "$DEST_BASE/sprites/ui"
mkdir -p "$DEST_BASE/textures"
mkdir -p "$DEST_BASE/videos"

echo "🎵 Moving Music Files..."
# Music themes (longer WAV files with descriptive names)
mv "$SOURCE_DIR/Sacred Spark.wav" "$DEST_BASE/audio/music/sacred_spark.wav" 2>/dev/null
mv "$SOURCE_DIR/Circle of Bright Mornings.wav" "$DEST_BASE/audio/music/menu_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Lion of the Dawn"*.wav "$DEST_BASE/audio/music/judah_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Incense in the Vaulted Air"*.wav "$DEST_BASE/audio/music/levi_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Caves and Hills of Promise.wav" "$DEST_BASE/audio/music/reuben_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Desert Sanctuary Main Theme.wav" "$DEST_BASE/audio/music/simeon_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Sunrise Over The Valley.wav" "$DEST_BASE/audio/music/naphtali_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Gather the Tribes"*.wav "$DEST_BASE/audio/music/lobby_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/Gathering at the Gates"*.wav "$DEST_BASE/audio/music/finale_theme.wav" 2>/dev/null
mv "$SOURCE_DIR/finale'"*.wav "$DEST_BASE/audio/music/" 2>/dev/null

echo "🔊 Moving Sound Effects..."
# SFX files (shorter, descriptive names)
mv "$SOURCE_DIR/Soft Tap of Yes.wav" "$DEST_BASE/audio/sfx/tap.wav" 2>/dev/null
mv "$SOURCE_DIR/Soft Stone Discovery.wav" "$DEST_BASE/audio/sfx/stone_unlock.wav" 2>/dev/null
mv "$SOURCE_DIR/ui_open.wav"*.wav "$DEST_BASE/audio/sfx/ui_open.wav" 2>/dev/null

# Combined SFX files (need to be split manually)
mv "$SOURCE_DIR/"*footstep*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*chest_open*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*heart_badge*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*ui_close*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*success*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*fail*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*timer*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*minigame*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*elder_murmur*.wav "$DEST_BASE/audio/sfx/voice/" 2>/dev/null
mv "$SOURCE_DIR/"*child_murmur*.wav "$DEST_BASE/audio/sfx/voice/" 2>/dev/null
mv "$SOURCE_DIR/"*neutral_murmur*.wav "$DEST_BASE/audio/sfx/voice/" 2>/dev/null
mv "$SOURCE_DIR/"*pickup*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*lobby*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*rhythm*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null
mv "$SOURCE_DIR/"*butterfly*.wav "$DEST_BASE/audio/sfx/" 2>/dev/null

echo "🎬 Moving Videos..."
mv "$SOURCE_DIR/"*.mp4 "$DEST_BASE/videos/" 2>/dev/null
mv "$SOURCE_DIR/"*.webm "$DEST_BASE/videos/" 2>/dev/null

echo "🖼️ Moving Images..."
# Move all JPG files to textures for manual sorting
mv "$SOURCE_DIR/"*.jpg "$DEST_BASE/textures/" 2>/dev/null
mv "$SOURCE_DIR/"*.jpeg "$DEST_BASE/textures/" 2>/dev/null

echo "📐 Moving Diagrams..."
mv "$SOURCE_DIR/"*.svg "$DEST_BASE/sprites/ui/" 2>/dev/null

echo "✅ Organization complete!"
echo ""
echo "📋 Next Steps:"
echo "1. Review audio files in assets/audio/sfx/ - some are combined and need splitting"
echo "2. Sort images in assets/textures/ into characters/backgrounds/ui folders"
echo "3. Import .import files will be auto-generated by Godot"
echo "4. Test audio in-game to verify quality"
